### ISSUE TITLE
Pysam error

### ISSUE THREAD

**Issue by szsctt** [hoffmangroup/polyidus#8]
I cloned polyidus and tried to run it on the sample data, but I got an error:
```
Traceback (most recent call last):
  File "polyidus.py", line 139, in <module>
    args.outdir, args.aligner, args.virname, args.skip_alignment)
  File "polyidus.py", line 84, in main
    polyidusObj.find_exact_integrations()
  File "/scratch1/polyidus/src/utils.py", line 1007, in find_exact_integrations
    start_host, readnames)
  File "/scratch1/polyidus/src/utils.py", line 91, in get_host_pos
    chromsize = bam.header.get_reference_length(chromhost)
AttributeError: 'dict' object has no attribute 'get_reference_length'
```

Looks to me like a pysam issue, but I'm using v0.8.4 (with python 3.4) as suggested.

**Comment by szsctt** [comment]
Changing line 91 in `utils.py` from 
```
chromsize = bam.header.get_reference_length(chromhost)
```
to 
```
chromsize = bam.lengths[bam.references.index(chromhost)]
```
fixed this issue for me.

**Comment by mehrankr** [comment]
Unfortunately this was a pysam version issue. Polyidus now requires pysam >= 0.15 and this is added to the documentation.
